### ISSUE TITLE
Failed to install on Centos7

### ISSUE THREAD

**Issue by stevemcquaid** [morganfainberg/positional#16]
```
$ pip install positional

Collecting positional
  Using cached positional-1.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/pbr/core.py", line 109, in pbr
        attrs = util.cfg_to_args(path)
      File "/usr/lib/python2.7/site-packages/pbr/util.py", line 261, in cfg_to_args
        wrap_commands(kwargs)
      File "/usr/lib/python2.7/site-packages/pbr/util.py", line 541, in wrap_commands
        for cmd, _ in dist.get_command_list():
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 447, in get_command_list
        cmdclass = ep.resolve()
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2208, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
    ImportError: No module named release
    error in setup command: Error parsing /tmp/pip-build-OYd1HL/positional/setup.cfg: ImportError: No module named release

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-OYd1HL/positional/


```
I am guessing this is an issue with not having version/release named explicitly in setup.cfg. Debugging further now.

**Comment by morganfainberg** [comment]
Good to know. PBR should handle that, but I could see where it might be an issue. Let me know what you find (I'll see if I can dig into the issue if you don't have an update on your debugging first).

**Comment by morganfainberg** [comment]
@stevemcquaid I had one of the folks in Keystone try it and got http://fpaste.org/343515/85976561/ Not sure where the differences are.

**Comment by stevemcquaid** [comment]
It could be that their global python install has more dependencies than what positional/requirements.txt has? Could do they do a pip freeze before creating the virtualenv?

**Comment by morganfainberg** [comment]
It looks like you're having an issue installing PBR based on the traceback. Their virtualenv is brand-new.

**Comment by stevemcquaid** [comment]
hmm that is interesting. It installs for me within a virtualenv, but fails if it is outside of a virtualenv.

**Comment by stevemcquaid** [comment]
Its definitely an environment issue - but I am a little concerned that it mandates installing within a virtualenv (which will make deploying on docker for example, much more complex.)

**Comment by morganfainberg** [comment]
Check to see what version of PBR you have and if it's something supplied by pip or by a package. I'm feeling like this is related to that first and foremost.

**Comment by stevemcquaid** [comment]
`pip freeze` outside of virtualenv gives:
pbr==1.8.1

**Comment by morganfainberg** [comment]
So we ran into this with another install and it turns out that the system installed setuptools was the issue. You're going to need to ensure that the correct (new) setup tools is installed.  

This is why the VENV method works, it has the new setuptools with the correct behavior.

**Comment by zohaibtechknox** [comment]
i know this is a close issue but i am having this issue in chroot enviornment when i try to install positional . I have upgrade setuptools with pip install --upgrade setuptools but still I have this issue. can some one explain what is exact solution for this..
