### ISSUE TITLE
unable to install in chroot environment on Centos 7

### ISSUE THREAD

**Issue by zohaibtechknox** [morganfainberg/positional#22]
I am unable to install positional in chroot environment on centos 7 . here is my issue 
`Collecting positional
  Downloading http://192.168.200.201:3141/root/pypi/+f/c82/903c32c1aec1a/positional-1.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-pRQAln/positional/setup.py", line 20, in <module>
        import multiprocessing  # noqa
      File "/usr/lib64/python2.7/multiprocessing/__init__.py", line 64, in <module>
        from multiprocessing.process import Process, current_process, active_children
      File "/usr/lib64/python2.7/multiprocessing/process.py", line 312, in <module>
        _current_process = _MainProcess()
      File "/usr/lib64/python2.7/multiprocessing/process.py", line 309, in __init__
        self._authkey = AuthenticationString(os.urandom(32))
    NotImplementedError: /dev/urandom (or equivalent) not found
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-pRQAln/positional/`
I know this issue is already address but there is no proper solution . @morganfainberg @jamielennox

**Comment by jamielennox** [comment]
I don't think this is positional's fault. So the import multiprocessing is unnecessary in python >= 2.7.4 and we could just not import it according to the comment, however multiprocessing is a standard platform dependency and it should be safe to import. 

Based on your comment i think you have not mapped /dev/urandom into the chroot you've created and this is a required file of the interpretter. Based on some googling try: 

`mknod /path/to/chroot/dev/urandom c 1 9 `

to add urandom specifically to your chroot or you could mount --bind the whole /dev directory. But basically if `import multiprocessing` is failing I think there is something wrong with your environment.

**Comment by zohaibtechknox** [comment]
Thanks This thing solve my issue

**Comment by morganfainberg** [comment]
Looks like this was solved via the information from @jamielennox. I am closing this issue.
