### ISSUE TITLE
FYI: discussion on python-ideas

### ISSUE THREAD

**Issue by haypo** [morganfainberg/positional#23]
Hi,

I just found your project from https://twitter.com/juldanjou/status/836601875252273152 tweet which dislikes your project.

FYI I started a thread on python-ideas to discuss putting this feature directly into the Python language: https://mail.python.org/pipermail/python-ideas/2017-February/044879.html

Enjoy!

**Comment by morganfainberg** [comment]
This can already be done in python3, and cleanly. This is only used in the case of python2/3 compat needs.

In python3 you can do:

`>>> def fn(pos1, *, kwonly1, kwonly2=None):
...     ...`

In short, don't use this library if you only use python3 (and you should care more about py3 than py2)
