### ISSUE TITLE
WARN enforcement method should be DeprecationError

### ISSUE THREAD

**Issue by jamielennox** [morganfainberg/positional#8]
Using enforce=WARN prints a warning message via logging. This made sense from a keystone perspective when the warning was coming from within the module however it will now be coming from a third party library that people shouldn't have to filter specifically. 

We should change WARN to use warnings DeprecationError for proper handling. 

I'm not sure how this affects keystone integration, do we still need to provide a logging method? Probably raising DeprecationWarning is what should have happened all along.

**Comment by morganfainberg** [comment]
Sounds good to me. Lets do this before we roll this to the first release on pypi

**Comment by morganfainberg** [comment]
Closed with PR #13
